CREATE DATABASE cadastrocliente;
USE cadastrocliente;
CREATE TABLE usuarios(
id INT(11) NOT NULL AUTO_INCREMENT,
nome VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
senha VARCHAR(50) NOT NULL,
dataCadastro DATE DEFAULT NULL,
PRIMARY KEY (id)
);
